# See http://www.appveyor.com/docs/appveyor-yml for many more options
version: 1.3.2.{build}
image: WMF 5
build: off
deploy:
- provider: NuGet
  server: https://ps.cloudcords.com:4433/nuget/CloudCords
  api_key:
    secure: kirERfZ/xAYSgvnKbFclvqHvdIeYdt/SkRCfj7Swjh0=
skip_commits:
  message: /updated readme.*|update readme.*s/

#Kick off the CI/CD pipeline
test_script:
  - ps: . .\build.ps1

#!deploy