version: 1.3.2.{build}
image: WMF 5
build: off
test_script:
- ps: .\build.ps1
deploy:
- provider: NuGet
  server: https://ps.cloudcords.com:4433/nuget/CloudCords
  api_key:
    secure: kirERfZ/xAYSgvnKbFclvqHvdIeYdt/SkRCfj7Swjh0=