# See http://www.appveyor.com/docs/appveyor-yml for many more options

environment:
version: 1.2.1.{build}

build:

  verbosity: minimal

deploy:

- provider: NuGet

  server: https://ps.cloudcords.com:4433/nuget/CloudCordsRepository

  api_key:

    secure: h0l79oAJkHZ7S4Qvcm1BdSuAQY1MU+Jj8dkcSZUV68E=

#  NugetApiKey:
#    secure: h0l79oAJkHZ7S4Qvcm1BdSuAQY1MU+Jj8dkcSZUV68E=
#  access_token:
#    secure: QelnrMKabQm4TFKxppcR+Vd5BNijYKoEPcEKu5CvvIHtsnup4F9f56/FQv+SNjkA

# Allow WMF5 (i.e. PowerShellGallery functionality)
os: WMF 5

# Skip on updates to the readme.
# We can force this by adding [skip ci] or [ci skip] anywhere in commit message 
skip_commits:
  files:
    - README.md
  message: /updated readme.*|update readme.*s|update docs.*|update version.*|update appveyor.*/


build: false

#Kick off the CI/CD pipeline
test_script:
  - ps: . .\build.ps1