version: 1.4.{build}
image: Visual Studio 2017
build: off
test_script:
- ps: . .\build\Start-Build.ps1 -Task Deploy
deploy:
- provider: NuGet
  server: https://ps.cloudcords.com:4433/nuget/CloudCords/
  api_key:
    secure: kirERfZ/xAYSgvnKbFclvqHvdIeYdt/SkRCfj7Swjh0=