# See http://www.appveyor.com/docs/appveyor-yml for many more options
version: 1.4.{build}
image: WMF 5
build: off
test_script:
- ps: .\build.ps1
deploy:
- provider: NuGet
  server: https://ps.cloudcords.com:4433/nuget/CloudCords/
  api_key:
    secure: kirERfZ/xAYSgvnKbFclvqHvdIeYdt/SkRCfj7Swjh0=WMF 5

# Skip on updates to the readme.
# We can force this by adding [skip ci] or [ci skip] anywhere in commit message 
skip_commits:
  files:
    - README.md
  message: /updated readme.*|update readme.*s|update docs.*|update version.*|update appveyor.*/