# See http://www.appveyor.com/docs/appveyor-yml for many more options
version: 1.0.0-build-{build}
image: Visual Studio 2017
deploy:
- provider: NuGet
  server: https://ps.cloudcords.com:4433/nuget/PoShCloudCords
  api_key:
    secure: 8DMu9tr7/CA0Ycl+7xPJgihrS0eFo3x3EK+qVRCFPwg=

image: Visual Studio 2017

# Skip on updates to the readme.
# We can force this by adding [skip ci] or [ci skip] anywhere in commit message 
skip_commits:
  message: /updated readme.*|update readme.*s/

build: false

#Kick off the CI/CD pipeline
test_script:
  - ps: . .\build.ps1