# See http://www.appveyor.com/docs/appveyor-yml for many more options
version: 1.3.1.{build}
deploy:
- provider: NuGet
  server: https://ps.cloudcords.com:4433/nuget/CloudCordsRepository
environment:
  NugetApiKey:
    secure: kirERfZ/xAYSgvnKbFclvqHvdIeYdt/SkRCfj7Swjh0=
  #access_token:
  #  secure: QelnrMKabQm4TFKxppcR+Vd5BNijYKoEPcEKu5CvvIHtsnup4F9f56/FQv+SNjkA

# Allow WMF5 (i.e. PowerShellGallery functionality)
os: WMF 5

# Skip on updates to the readme.
# We can force this by adding [skip ci] or [ci skip] anywhere in commit message 
skip_commits:
  message: /updated readme.*|update readme.*s/
build: off

#Kick off the CI/CD pipeline
test_script:
- ps: . .\build.ps1

#deploy