site_name: PSMSGraph - PowerShell Module for the Microsoft Graph API
repo_url: https://github.com/markekraus/PSMSGraph
site_author: Mark Kraus
edit_uri: edit/master/docs/
theme: readthedocs
copyright: "PSMSGraph is licensed under the <a href='https://github.com/markekraus/PSMSGraph/raw/master/LICENSE'>MIT license"
pages:
  - Home: index.md




  site_name: PoShCloudCords - PowerShell Module for the CloudCords DevOps team
repo_url: https://github.com/th3br3t/PoShCloudCords
site_author: Bret Robinson
edit_uri: edit/master/docs/
theme: readthedocs
copyright: "PoShCloudCords is licensed under the <a href='https://github.com/th3br3t/PoShCloudCords/blob/master/LICENSE'>MIT license"
pages:
  - Home: index.md