site_name: PoShCloudCords - PowerShell Module for the CloudCords DevOps team
repo_url: https://tfs.cloudcords.com/CloudCordsCollection/DevOps/_git/Infrastructure/Shared/Modules/PoSHCloudCords
site_author: Bret Robinson
edit_uri: edit/master/docs/
theme: readthedocs
copyright: "PoShCloudCords is licensed under the <a href='https://github.com/th3br3t/PoShCloudCords/blob/master/LICENSE'>MIT license"
nav:
  - Home: index.md
  - Realse Notes: RELEASE.md
  - Change Log: ChangeLog.md
  - Functions:
    - Import-PSCredential: functions/Import-PSCredential.md